name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1

      - name: Build docs
        run: |
          lake update Logic
          lake build Logic:docs
        working-directory: docbuild
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docbuild/.lake/build/doc"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4